# general settings
name: train_DiffRIRS1_x1
model_type: DiffRIRS1Model
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 8 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRNetModel ----------------- #
gt_usm: False  # USM the ground-truth

# the first degradation process
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [30, 95]

# the second degradation process
second_blur_prob: 0.8
resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [30, 95]

gt_size: 256
queue_size: 160

# dataset and data loader settings
datasets:
  train:
    name: DF2K+OST
    type: DiffRIRYMaskDataset
    dataroot_gt: /mnt/bn/xiabinpaint/dataset
    meta_info: datasets/meta_info/meta_info_DF2Kmultiscale+OST_sub.txt
    io_backend:
      type: disk
    mask_kind: mixed
    Y_error: 0.06
    Y_bias: 0.05
    mask_kwargs: 
        irregular_proba: 0.35
        irregular_kwargs:
          max_angle: 4 
          max_len: 240
          max_width: 100
          max_times: 4 
          min_times: 1
        box_proba: 0.3
        box_kwargs:
          margin: 10
          bbox_min_size: 35
          bbox_max_size: 160
          max_times: 4
          min_times: 1
        outpainting_proba: 0.35
        outpainting_kwargs:
          min_padding_percent: 0.15
          max_padding_percent: 0.4 
          left_padding_prob: 0.5
          top_padding_prob: 0.5
          right_padding_prob: 0.5
          bottom_padding_prob: 0.5

    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

    gt_size: 256
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 5
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val_1:
    name: NTIRE2020-Track1
    type: DiffIRMaskPairedImageDataset
    dataroot_gt: /mnt/bn/xiabinpaint/dataset/NTIRE2020-Track1/track1-valid-gt
    dataroot_lq: /mnt/bn/xiabinpaint/dataset/NTIRE2020-Track1/lrx4_addy
    dataroot_mask: /mnt/bn/xiabinpaint/dataset/NTIRE2020-Track1/MASK
    io_backend:
      type: disk

# network structures
network_g:
  type: DiffRIRS1
  n_encoder_res: 9
  inp_channels: 6
  out_channels: 3
  scale: 1
  dim: 64
  num_blocks: [13,1,1,1]
  num_refinement_blocks: 13
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.2
  bias: False
  LayerNorm_type: BiasFree

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000,300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  window_size: 32
  val_freq: !!float 5e4
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
